name: Choria Packager Executer
description: Uses the Choria Packager to package Go code into aartifacts
inputs:
  build_package:
    description: The package name to build as defined in buildspec.yaml
    required: true

  packager_tag:
    description: The packager tag to use when building
    required: true

  version:
    description: The version to compile
    required: true

  build:
    description: The build definition from buildspec.yaml to use
    default: foss
    required: false

  go_package:
    description: The go package to build, eg. github.com/choria-io/go-choria
    required: false
    default: "github.com/${GITHUB_REPOSITORY}"

  source_directory:
    description: Where the Go code is to build
    default: src
    required: true

  artifacts_directory:
    description: The directory holding artifacts
    required: false
    default: artifacts

runs:
  using: composite
  steps:
    - shell: bash --noprofile --norc -x -e -o pipefail {0}
      run: |
        mkdir -p "${{ inputs.artifacts_directory }}/${{ inputs.build_package }}"

        _version="${{ inputs.version }}"
        if [ $_version = "nightly" ]
        then
          _version="0.99.0.$(date +'%Y%m%d')"
        fi

        docker run \
          --rm \
          -v `pwd`/${{ inputs.source_directory }}/${{ inputs.go_package }}:/go/src/${{ inputs.go_package }} \
          -v `pwd`/${{ inputs.artifacts_directory }}:/artifacts \
          -e SOURCE_DIR=/go/src/${{ inputs.go_package }} \
          -e SHA1=${GITHUB_SHA} \
          -e BUILD=${{ inputs.build }} \
          -e VERSION="$_version" \
          -e ARTIFACTS="/artifacts/${{ inputs.build_package }}" \
          -e PACKAGE=${{ inputs.build_package }} \
          choria/packager:${{ inputs.packager_tag }}

        ls -lR "${{ inputs.artifacts_directory }}/${{ inputs.build_package }}"

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.build }}
        retention-days: 5
        path: |
          ${{ inputs.artifacts_directory }}
          !${{ inputs.artifacts_directory }}/**/*.src.rpm

