name: Build Packager
description: Builds a packager docker container

inputs:
  go:
    description: The version of go to build
    required: true

  tag:
    description: The container tag
    required: true

  file:
    description: The Dockerfile
    required: true

  hub_user:
    descriotion: Docker hub username
    required: true

  hub_password:
    descriotion: Docker hub username
    required: true

  platforms:
    description: Platforms to build
    required: true
    default: linux/amd64

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

    - name: Login to DockerHub
      uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
      with:
        registry: registry.choria.io
        username: ${{ inputs.hub_user }}
        password: ${{ inputs.hub_password }}

    - name: Build and push
      uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
      with:
        push: true
        tags: registry.choria.io/choria/packager:${{ inputs.tag }}
        platforms: ${{ inputs.platforms }}
        file: ${{ inputs.file }}
        build-args: |
          GOVERSION=${{ inputs.go }}
