name: Build Packager
description: Builds a packager docker container

inputs:
  go:
    description: The version of go to build
    required: true

  tag:
    description: The container tag
    required: true

  file:
    description: The Dockerfile
    required: true

  hub_user:
    descriotion: Docker hub username
    required: true

  hub_password:
    descriotion: Docker hub username
    required: true

  platforms:
    description: Platforms to build
    required: true
    default: linux/amd64

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        registry: registry.choria.io
        username: ${{ inputs.hub_user }}
        password: ${{ inputs.hub_password }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: registry.choria.io/choria/packager:${{ inputs.tag }}
        platforms: ${{ inputs.platforms }}
        file: ${{ inputs.file }}
        build-args: |
          GOVERSION=${{ inputs.go }}
